name: Build and Release

on:
  push:
    branches:
      - master
      - build-test

jobs:
  Build-and-Release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get Version
        id: version
        run: |
          echo "##[set-output name=version;]$(cat VERSION)"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.version }}
          release_name: ${{ steps.version.outputs.version }}
          draft: true
          prerelease: false
      
      - name: Build for Windows
        uses: ./.github/actions/Build-Windows
        with:
          version: ${{ steps.version.outputs.version }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}
      
      - name: Build for Linux
        uses: ./.github/actions/Build-Linux
        with:
          version: ${{ steps.version.outputs.version }}
          upload_url: ${{ steps.create_release.outputs.upload_url }}
